### ISSUE TITLE
Building examples on Fedora w/ Clang 3.2 (git)

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#29]
I cannot get the examples to compile using Clang 3.2 (git) on Fedora Linux:

```
make[1]: Entering directory `/home/matthias/src/libcppa/build'
make[2]: Entering directory `/home/matthias/src/libcppa/build'
make[3]: Entering directory `/home/matthias/src/libcppa/build'
make[3]: Leaving directory `/home/matthias/src/libcppa/build'
[ 63%] Built target libcppa
make[3]: Entering directory `/home/matthias/src/libcppa/build'
make[3]: Leaving directory `/home/matthias/src/libcppa/build'
make[3]: Entering directory `/home/matthias/src/libcppa/build'
[ 64%] Building CXX object unit_testing/CMakeFiles/unit_tests.dir/ping_pong.cpp.o
/home/matthias/src/libcppa/unit_testing/ping_pong.cpp:46:24: error: no viable overloaded '='
            init_state = (
            ~~~~~~~~~~ ^ ~
/home/matthias/src/libcppa/./cppa/behavior.hpp:61:15: note: candidate function not viable: no known conversion from 'match_expr<cppa::detail::projection_partial_function_pair<cppa::util::type_list<cppa::atom_value, int>, cppa::detail::projection<cppa::util::type_list<cppa::util::void_type, cppa::util::void_type>, const cppa::atom_value &, const int &>, cppa::tpartial_function<impl::<lambda at /home/matthias/src/libcppa/unit_testing/ping_pong.cpp:47:44>, cppa::detail::value_guard<cppa::util::type_list<cppa::atom_value> >, void, const cppa::atom_value &, int> >, cppa::detail::projection_partial_function_pair<cppa::util::type_list<cppa::anything>, cppa::detail::projection<util::empty_type_list>, cppa::tpartial_function<impl::<lambda at /home/matthias/src/libcppa/unit_testing/ping_pong.cpp:57:29>, cppa::detail::value_guard<cppa::util::type_list<> >, void, > > >' to 'cppa::behavior' for 1st argument; 
    behavior& operator=(behavior&&) = default;
              ^
/home/matthias/src/libcppa/./cppa/behavior.hpp:62:15: note: candidate function not viable: no known conversion from 'match_expr<cppa::detail::projection_partial_function_pair<cppa::util::type_list<cppa::atom_value, int>, cppa::detail::projection<cppa::util::type_list<cppa::util::void_type, cppa::util::void_type>, const cppa::atom_value &, const int &>, cppa::tpartial_function<impl::<lambda at /home/matthias/src/libcppa/unit_testing/ping_pong.cpp:47:44>, cppa::detail::value_guard<cppa::util::type_list<cppa::atom_value> >, void, const cppa::atom_value &, int> >, cppa::detail::projection_partial_function_pair<cppa::util::type_list<cppa::anything>, cppa::detail::projection<util::empty_type_list>, cppa::tpartial_function<impl::<lambda at /home/matthias/src/libcppa/unit_testing/ping_pong.cpp:57:29>, cppa::detail::value_guard<cppa::util::type_list<> >, void, > > >' to 'const cppa::behavior' for 1st argument; 
    behavior& operator=(const behavior&) = default;
              ^
/home/matthias/src/libcppa/unit_testing/ping_pong.cpp:91:24: error: no viable overloaded '='
            init_state = (
            ~~~~~~~~~~ ^ ~
/home/matthias/src/libcppa/./cppa/behavior.hpp:61:15: note: candidate function not viable: no known conversion from 'match_expr<cppa::detail::projection_partial_function_pair<cppa::util::type_list<cppa::atom_value, int>, cppa::detail::projection<cppa::util::type_list<cppa::util::void_type, cppa::util::void_type>, const cppa::atom_value &, const int &>, cppa::tpartial_function<impl::<lambda at /home/matthias/src/libcppa/unit_testing/ping_pong.cpp:92:44>, cppa::detail::value_guard<cppa::util::type_list<cppa::atom_value> >, void, const cppa::atom_value &, int> >, cppa::detail::projection_partial_function_pair<cppa::util::type_list<cppa::anything>, cppa::detail::projection<util::empty_type_list>, cppa::tpartial_function<impl::<lambda at /home/matthias/src/libcppa/unit_testing/ping_pong.cpp:96:29>, cppa::detail::value_guard<cppa::util::type_list<> >, void, > > >' to 'cppa::behavior' for 1st argument; 
    behavior& operator=(behavior&&) = default;
              ^
/home/matthias/src/libcppa/./cppa/behavior.hpp:62:15: note: candidate function not viable: no known conversion from 'match_expr<cppa::detail::projection_partial_function_pair<cppa::util::type_list<cppa::atom_value, int>, cppa::detail::projection<cppa::util::type_list<cppa::util::void_type, cppa::util::void_type>, const cppa::atom_value &, const int &>, cppa::tpartial_function<impl::<lambda at /home/matthias/src/libcppa/unit_testing/ping_pong.cpp:92:44>, cppa::detail::value_guard<cppa::util::type_list<cppa::atom_value> >, void, const cppa::atom_value &, int> >, cppa::detail::projection_partial_function_pair<cppa::util::type_list<cppa::anything>, cppa::detail::projection<util::empty_type_list>, cppa::tpartial_function<impl::<lambda at /home/matthias/src/libcppa/unit_testing/ping_pong.cpp:96:29>, cppa::detail::value_guard<cppa::util::type_list<> >, void, > > >' to 'const cppa::behavior' for 1st argument; 
    behavior& operator=(const behavior&) = default;
              ^
2 errors generated.
make[3]: *** [unit_testing/CMakeFiles/unit_tests.dir/ping_pong.cpp.o] Error 1
make[3]: Leaving directory `/home/matthias/src/libcppa/build'
make[2]: *** [unit_testing/CMakeFiles/unit_tests.dir/all] Error 2
make[2]: Leaving directory `/home/matthias/src/libcppa/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/matthias/src/libcppa/build'
make: *** [all] Error 2
     ^
```

Any ideas?
