### ISSUE TITLE
Qt examples doesn't build in master and 0.18.0-rc.1 tag

### ISSUE THREAD

**Issue by melg8** [actor-framework/actor-framework#1156]
# Steps to reproduce
1. git clone https://github.com/actor-framework/actor-framework
2. cd actor-framework
3. git checkout master
4. ./configure --prefix=/usr --enable-qt5-examples
5. cd build
6. make

# Expected behavior
Build should finish with no errors

# Observed behavior
Build fails with error messages:
```

actor-framework/examples/qtsupport/chatwidget.hpp:25:30: error: ‘atom_constant’ in namespace ‘caf’ does not name a template type
   using set_name_atom = caf::atom_constant<caf::atom("setName")>;

actor-framework/examples/qtsupport/qt_group_chat.cpp:77:29: error: ‘atom’ was not declared in this scope
     send_as(client, client, atom("setName"), move(name));
```

Maybe there are other examples which doesn't build now, didn't check yet.
Updates:
- protobuf example have this issue too.
- In Qt example core issues are:
   * usage of old caf::(atom("something")) syntax
   * usage of dynamic dispatch on string as atoms `mb.append(atom_from_string(words.front()))`
   * inconsisten behaviour of split function, due to inconsistent behaviour of caf::span (gcc version has constructor overload for const char * and clang - doesn't - inspect #ifdef CAF_GCC)

**Comment by Neverlord** [comment]
Thanks for reporting! It's easy to miss this, since the Qt examples aren't build by our CI. We should also fix that while we're on it.

**Comment by melg8** [comment]
In addition:
- comments in examples are out of sync, for example the reffer to "./build/bin/group_server -p 4242" - but now examples are in ./build/examples directory
- at least group chat example doesn't work.
After running "group_server -p 4242", i've tried to run "group_chat -g remote:chatroom@localhost:4242 -n alice"
and here is output:
```
*** starting client, type '/help' for a list of commands
*** failed to parse "remote:chatroom@localhost:4242" as group URI: caf::sec(no_such_group_module)message("no module named \"remote\" found")
```
