### PR TITLE
Fix qt and protobuf examples

### LINKED ISSUE #1156: Qt examples doesn't build in master and 0.18.0-rc.1 tag
# Steps to reproduce
1. git clone https://github.com/actor-framework/actor-framework
2. cd actor-framework
3. git checkout master
4. ./configure --prefix=/usr --enable-qt5-examples
5. cd build
6. make

# Expected behavior
Build should finish with no errors

# Observed behavior
Build fails with error messages:
```

actor-framework/examples/qtsupport/chatwidget.hpp:25:30: error: ‘atom_constant’ in namespace ‘caf’ does not name a template type
   using set_name_atom = caf::atom_constant<caf::atom("setName")>;

actor-framework/examples/qtsupport/qt_group_chat.cpp:77:29: error: ‘atom’ was not declared in this scope
     send_as(client, client, atom("setName"), move(name));
```

Maybe there are other examples which doesn't build now, didn't check yet.
Updates:
- protobuf example have this issue too.
- In Qt example core issues are:
   * usage of old caf::(atom("something")) syntax
   * usage of dynamic dispatch on string as atoms `mb.append(atom_from_string(words.front()))`
   * inconsisten behaviour of split function, due to inconsistent behaviour of caf::span (gcc version has constructor overload for const char * and clang - doesn't - inspect #ifdef CAF_GCC)

### PR DESCRIPTION
**Pull request by RG-707**
Closes #1156

### CODE REVIEW

File: examples/qtsupport/chatwidget.cpp [hunk 1]
```diff
@@ -68,30 +74,22 @@ void ChatWidget::sendChatMessage() {
...
-      mb.append(atom_from_string(words.front()))
-        .append(words.begin() + 1, words.end());
-    };
-    auto res = mb.apply({
-      [=](join_atom, const string& mod, const string& g) {
-        auto x = system().groups().get(mod, g);
-        if (! x)
+      if (words.front() == "join" && words.size() == 3) {
+        auto x = system().groups().get(words[1], words[2]);
+        if (!x)
```
Comment (Neverlord) [inline examples/qtsupport/chatwidget.cpp:80]:
```suggestion
        if (auto x = system().groups().get(words[1], words[2]))
```

And don't forget to switch the bodies for `if` and `else`. Generally, I think putting the "good" case first makes the code easier to follow.

File: examples/qtsupport/chatwidget.cpp [hunk 2]
```diff
@@ -68,30 +74,22 @@ void ChatWidget::sendChatMessage() {
...
         else
-          self()->send(self(), atom("join"), std::move(*x));
-      },
-      [=](set_name_atom atm, string& name) {
-        send_as(as_actor(), as_actor(), atm, std::move(name));
-      }
-    });
-    if (! res)
+          self()->send(self(), join_atom_v, std::move(*x));
+      } else if (words.front() == "setName" && words.size() == 2)
```
Comment (Neverlord) [inline examples/qtsupport/chatwidget.cpp:85]:
```suggestion
      } else if (words[0] == "setName" && words.size() == 2)
```

File: examples/qtsupport/chatwidget.hpp [hunk 3]
```diff
@@ -11,6 +11,13 @@ CAF_PUSH_WARNINGS
 #include <QTextEdit>
 CAF_POP_WARNINGS
 
+CAF_BEGIN_TYPE_ID_BLOCK(qt_support, first_custom_type_id)
```
Comment (Neverlord) [inline examples/qtsupport/chatwidget.hpp:14]:
```suggestion
CAF_BEGIN_TYPE_ID_BLOCK(qtsupport, first_custom_type_id)
```

I find it confusing to introduce an underscore here if the example directory does not.

File: examples/qtsupport/qt_group_chat.cpp [hunk 4]
```diff
@@ -4,9 +4,9 @@
  * terminal version in remote_actors/group_chat.cpp.                          *
  *                                                                            *
  * Setup for a minimal chat between "alice" and "bob":                        *
- * - ./build/bin/group_server -p 4242                                         *
- * - ./build/bin/qt_group_chat -g remote:chatroom@localhost:4242 -n alice     *
- * - ./build/bin/qt_group_chat -g remote:chatroom@localhost:4242 -n bob       *
+ * - ./build/examples/group_server -p 4242                                    *
+ * - ./build/examples/qt_group_chat -g remote:chatroom@localhost:4242 -n alice*
+ * - ./build/examples/qt_group_chat -g remote:chatroom@localhost:4242 -n bob  *
```
Comment (Neverlord) [inline examples/qtsupport/qt_group_chat.cpp:9]: Please drop the paths here as well.

File: examples/qtsupport/qt_group_chat.cpp [hunk 5]
```diff
@@ -26,57 +26,62 @@ CAF_PUSH_WARNINGS
...
-  auto name = cfg.name;
+  init_global_meta_objects<id_block::qt_support>();
+  core::init_global_meta_objects();
+  io::middleman::init_global_meta_objects();
+  config cfg{};
+  auto err = cfg.parse(argc, argv);
+  if (cfg.cli_helptext_printed)
+    return 0;
+  cfg.load<io::middleman>();
+  actor_system sys{cfg};
```
Comment (Neverlord) [inline examples/qtsupport/qt_group_chat.cpp:52]: Please use the `CAF_MAIN` scaffold here instead of making all of these steps by hand. This example simple hasn't been ported to it yet.

File: examples/qtsupport/qt_group_chat.cpp [hunk 6]
```diff
@@ -26,57 +26,62 @@ CAF_PUSH_WARNINGS
...
+  }
   group grp;
   // evaluate group parameters
-  if (! cfg.group_id.empty()) {
-    auto p = cfg.group_id.find(':');
-    if (p == std::string::npos) {
-      cerr << "*** error parsing argument " << cfg.group_id
-         << ", expected format: <module_name>:<group_id>";
+  if (auto locator = get_if<std::string>(&cfg, "group")) {
+    if (auto grp_p = sys.groups().get(*locator)) {
```
Comment (Neverlord) [inline examples/qtsupport/qt_group_chat.cpp:66]:
```suggestion
    if (auto grp_p = sys.groups().get(*locator)) {
```

What is the `_p` suffix standing for? In other places, we usually use a `maybe_` prefix for catching the result of something that returns `expected<T>` or `optional<T>`.

**Review by Neverlord — CHANGES_REQUESTED** [review]
Thanks for taking care of this! 🙏

Currently, this does not compile for me (see [fail.log](https://github.com/actor-framework/actor-framework/files/5569421/fail.log)). Also, this isn't covered by our CI. Please make sure that at least one build in our matrix includes the Qt5 examples.

I've also found a couple minor things in the code, mostly stylistically.

File: examples/qtsupport/qt_group_chat.cpp (hunk 5 above)
Comment (RG-707) [reply examples/qtsupport/qt_group_chat.cpp]: I will port it to `CAF_MAIN`.

**Comment by RG-707** [comment]
I will look into the build problems and add it to the CI.
