### ISSUE TITLE
intrusive_ptr.hpp:253:20: error: expected ‘)’ before ‘PRIxPTR’

### ISSUE THREAD

**Issue by Vxider** [actor-framework/actor-framework#705]
Hi, I'm using G++-6 to compile my app with caf, but I have  encountered a problem

```
intrusive_ptr.hpp:253:20: error: expected ‘)’ before ‘PRIxPTR’
```

**Comment by josephnoir** [comment]
Our last Jenkins build with gcc 6.3 on Linux [compiled and the tests succeeded](https://jenkins.inet.haw-hamburg.de/job/CAF/job/gcc/label_exp=Linux%20&&%20gcc6.3/860/console).

Could you provide a bit more information on your system and compiler version?

**Comment by Vxider** [comment]
my system centos 3.10, I have tried using gcc 4.9.2, 5.3.1, 6.2.1 and 8.1.0. All compilers can build success and 100% pass test cases. But when I compile my application, there is `"local/include/caf/intrusive_ptr.hpp:252:19: error：expected ‘)’ before ‘PRIxPTR’
"` problem. It seems the compiler cannot recognize symbol `PRIxPTR`.  CAF version 0.15.3 is OK, but the newer version 0.15.4-0.15.7 all have these problem

**Comment by Neverlord** [comment]
So much for relying on the C standard. *sigh*

@Vxider should be fixed, please re-open if you still get compiler errors in `intrusive_ptr.hpp`.
