### ISSUE TITLE
Compile with OpenSSL <= 1.0.1 is currently broken

### ISSUE THREAD

**Issue by Hamdor** [actor-framework/actor-framework#629]
Compilation with old versions of OpenSSL currently fails with:
```
SSL_CTX_set_ecdh_auto was not declared in this scope
```
this is due to `SSL_CTX_set_ecdh_auto`was firstly added to OpenSSL with version 1.0.2. We should add a proper handling for this.

**Comment by Neverlord** [comment]
This OpenSSL nonsense is getting on my nerves.
