### ISSUE TITLE
regression in caf::io::spawn_client

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1900]
While we didn't really touch the I/O module recently, something broke `spawn_client`. Code to reproduce:

```
  sys.middleman().spawn_client([](caf::io::broker*) {}, "foo", 42);
```

### Discussed in https://github.com/actor-framework/actor-framework/discussions/1899

<div type='discussions-op-text'>

<sup>Originally posted by **xliao-neology** June 27, 2024</sup>
we been using spawn_client() perfectly in 0.19.6. However same code will have below error show up in 1.0.0.
I understand the trend is to use caf_net. But for now, any way that I can do to keep spawn_client() work with 1.0.0 release?

>>>>>
/usr/local/include/caf/actor_storage.hpp:30:5: error: ‘caf::io::abstract_broker::abstract_broker(caf::actor_config&)’ is protected within this context
   30 |     new (&data) T(std::forward<Us>(zs)...);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</div>

**Comment by riemass** [comment]
All right, found the commit where we refactored some ctors, and caused this bug. I return the public ctor in the derived class, but I would much rather just add the `actor_storage` as a friend to the `abstract_broker`, as it was done in the `abstract_actor`. This should be ABI compatible (?). 
Also, the broker lambda functor requires a `connection_handle` in the signature:
``` cpp
  sys.middleman().spawn_client([](caf::io::broker*) {}, "foo", 42); // Doesn't compile.
  sys.middleman().spawn_client([](caf::io::broker*, caf::io::connection_handle) {}, "foo", 42); // Works. 
```
Is this a regression as well?

**Comment by xliao-neology** [comment]
> All right, found the commit where we refactored some ctors, and caused this bug. I return the public ctor in the derived class, but I would much rather just add the `actor_storage` as a friend to the `abstract_broker`, as it was done in the `abstract_actor`. This should be ABI compatible (?). Also, the broker lambda functor requires a `connection_handle` in the signature:
> 
> ```c++
>   sys.middleman().spawn_client([](caf::io::broker*) {}, "foo", 42); // Doesn't compile.
>   sys.middleman().spawn_client([](caf::io::broker*, caf::io::connection_handle) {}, "foo", 42); // Works. 
> ```
> 
> Is this a regression as well?

Thank you, it compile for me with the fix.

I quoted a past example function as below. So for the current fix, have to add default parameter value as below.
Is there any other better way?

>>>
behavior peer_fun(broker* self, connection_handle hdl = {}, const actor& buddy=nullptr) {
}
